export const technologies = [
  { name: "HTML", icon: "html5.svg" },
  { name: "CSS", icon: "css3.svg" },
  { name: "JavaScript", icon: "javascript.svg" },
  { name: "TypeScript", icon: "typescript.svg" },
  { name: "React", icon: "react.svg" },
  { name: "Redux", icon: "redux.svg" },
  { name: "Redis", icon: "redis.svg" },
  { name: "Bootstrap", icon: "bootstrap.svg" },
  { name: "Tailwind", icon: "tailwind.svg" },
  { name: "SASS", icon: "sass.svg" },
  { name: "Nodejs", icon: "nodejs.svg" },
  { name: "Dinojs", icon: "dinojs.svg" },
  { name: "bunjs", icon: "bunjs.svg" },
  { name: "MongoDB", icon: "mongodb.svg" },
  { name: "Mongoose", icon: "mongoose.svg" },
  { name: "Express.js", icon: "express.svg" },
  { name: "Webpack", icon: "webpack.svg" },
  { name: "Nextjs", icon: "nextjs.svg" },
];

export const techIcons = {
  Html: "html5.svg",
  Css: "css3.svg",
  Javascript: "javascript.svg",
  Typescript: "typescript.svg",
  React: "react.svg",
  Redux: "redux.svg",
  Redis: "redis.svg",
  Boostrap: "bootstrap.svg",
  Tailwind: "tailwind.svg",
  Sass: "sass.svg",
  Node: "nodejs.svg",
  Dino: "dinojs.svg",
  Bun: "bunjs.svg",
  Mongodb: "mongodb.svg",
  Mongoose: "mongoose.svg",
  Express: "express.svg",
  Webpack: "webpack.svg",
  Shopify: "shopify.svg",
  Next: "nextjs.svg",
  Appwrite: "appwrite.svg",
  Cloudinary: "cloudinary.svg",
};
