export const technologies = [
  { name: "HTML", icon: "html5.svg" },
  { name: "CSS", icon: "css3.svg" },
  { name: "JavaScript", icon: "javascript.svg" },
  { name: "TypeScript", icon: "typescript.svg" },
  { name: "React", icon: "react.svg" },
  { name: "Redux", icon: "redux.svg" },
  { name: "Redis", icon: "redis.svg" },
  { name: "Bootstrap", icon: "bootstrap.svg" },
  { name: "Tailwind", icon: "tailwind.svg" },
  { name: "SASS", icon: "sass.svg" },
  { name: "Nodejs", icon: "nodejs.svg" },
  { name: "Dinojs", icon: "dinojs.svg" },
  { name: "bunjs", icon: "bunjs.svg" },
  { name: "MongoDB", icon: "mongodb.svg" },
  { name: "Mongoose", icon: "mongoose.svg" },
  { name: "Express.js", icon: "express.svg" },
  { name: "Webpack", icon: "webpack.svg" },
];

export const techIcons = {
  html: "html5.svg",
  css: "css3.svg",
  javascript: "javascript.svg",
  typescript: "typescript.svg",
  react: "react.svg",
  redux: "redux.svg",
  redis: "redis.svg",
  boostrap: "bootstrap.svg",
  tailwind: "tailwind.svg",
  sass: "sass.svg",
  node: "nodejs.svg",
  dino: "dinojs.svg",
  bun: "bunjs.svg",
  mongodb: "mongodb.svg",
  mongoose: "mongoose.svg",
  express: "express.svg",
  webpack: "webpack.svg",
  shopify: "shopify.svg",
  next: "nextjs.svg",
  appwrite: "appwrite.svg",
  cloudinary: "cloudinary.svg",
};
